# Generated by scripts/update-brew-tap.sh in pypestream/maestro-compiler — do
# not edit by hand. Installs the prebuilt maestro compiler binary from the
# Pypestream distribution (CloudFront over a private S3 origin).
class Maestro < Formula
  desc "Compiler for the Pypestream Maestro DSL"
  homepage "https://github.com/pypestream/maestro-compiler"
  version "0.0.0"
  license "Proprietary"

  # Seeded placeholder: no build has been published to maestro-cli.main.pypestream.dev
  # yet. The 0.4.0 tag rewrites this file with real URLs and checksums.
  disable! date: "2026-09-23", because: "has not been published to the Pypestream distribution yet"

  if OS.mac?
    if Hardware::CPU.arm?
      url "https://maestro-cli.main.pypestream.dev/0.0.0/maestro-darwin-arm64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    else
      url "https://maestro-cli.main.pypestream.dev/0.0.0/maestro-darwin-amd64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  else
    if Hardware::CPU.arm?
      url "https://maestro-cli.main.pypestream.dev/0.0.0/maestro-linux-arm64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    else
      url "https://maestro-cli.main.pypestream.dev/0.0.0/maestro-linux-amd64"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    binary = if OS.mac?
      Hardware::CPU.arm? ? "maestro-darwin-arm64" : "maestro-darwin-amd64"
    else
      Hardware::CPU.arm? ? "maestro-linux-arm64" : "maestro-linux-amd64"
    end
    bin.install binary => "maestro"
  end

  test do
    system "#{bin}/maestro", "version"
  end
end
