# Generated by scripts/update-brew-tap.sh — do not edit by hand.
# Installs the prebuilt maestro compiler binary from the Pypestream
# distribution at maestro-cli.main.pypestream.dev (census 6c).
class Maestro < Formula
  desc "Compiler for the Pypestream Maestro DSL"
  homepage "https://github.com/pypestream/maestro-compiler"
  version "0.4.0"
  license "Proprietary"

  if OS.mac?
    if Hardware::CPU.arm?
      url "https://maestro-cli.main.pypestream.dev/0.4.0/maestro-darwin-arm64"
      sha256 "b193fc0bd5686ac42f8aa6e8ac5b375e14658e2ed6247172a0cc2323a37135ac"
    else
      url "https://maestro-cli.main.pypestream.dev/0.4.0/maestro-darwin-amd64"
      sha256 "4c99b1fe4d4edda087d851385468824c75a3a91ae1c68cb4c1374ffb416c35db"
    end
  else
    if Hardware::CPU.arm?
      url "https://maestro-cli.main.pypestream.dev/0.4.0/maestro-linux-arm64"
      sha256 "c3b4f610c04f3ea5dc947751c3441d777cc85b22cd008d5a2e25da3d3036baef"
    else
      url "https://maestro-cli.main.pypestream.dev/0.4.0/maestro-linux-amd64"
      sha256 "ccaa5f431e9a70248137147a9c06a4f08ba25fa85dfb30cb947de3fb7d39e26a"
    end
  end

  def install
    binary = if OS.mac?
      Hardware::CPU.arm? ? "maestro-darwin-arm64" : "maestro-darwin-amd64"
    else
      Hardware::CPU.arm? ? "maestro-linux-arm64" : "maestro-linux-amd64"
    end
    bin.install binary => "maestro"
  end

  test do
    system "#{bin}/maestro", "version"
  end
end
