# Generated by scripts/update-brew-tap.sh — do not edit by hand.
# Installs the prebuilt maestro compiler binary from the Pypestream
# distribution at maestro-cli.main.pypestream.dev (census 6c).
class Maestro < Formula
  desc "Compiler for the Pypestream Maestro DSL"
  homepage "https://github.com/pypestream/maestro-compiler"
  version "0.4.1"
  license "Proprietary"

  if OS.mac?
    if Hardware::CPU.arm?
      url "https://maestro-cli.main.pypestream.dev/0.4.1/maestro-darwin-arm64"
      sha256 "b7a312d43774676be1d111b495764bbb91e8329e1a27eb2ec6c5810b28cf977f"
    else
      url "https://maestro-cli.main.pypestream.dev/0.4.1/maestro-darwin-amd64"
      sha256 "8702562cf8312603eaaf7b3d153d858115727bc5741f36e9dac21e37f85da2a7"
    end
  else
    if Hardware::CPU.arm?
      url "https://maestro-cli.main.pypestream.dev/0.4.1/maestro-linux-arm64"
      sha256 "12db6f0cea7faecdcbbe0e306bbfe701b5615f7b0cd99cbbb0798d1a582c6568"
    else
      url "https://maestro-cli.main.pypestream.dev/0.4.1/maestro-linux-amd64"
      sha256 "2e043c7bf61d085102d426d31b201e99bb5e88692afcb6a449b4bca27910e0b2"
    end
  end

  def install
    binary = if OS.mac?
      Hardware::CPU.arm? ? "maestro-darwin-arm64" : "maestro-darwin-amd64"
    else
      Hardware::CPU.arm? ? "maestro-linux-arm64" : "maestro-linux-amd64"
    end
    bin.install binary => "maestro"
  end

  test do
    system "#{bin}/maestro", "version"
  end
end
